name: C Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt update && sudo apt install build-essential
    - name: Compile C programs
      run: gcc your_program.c -o your_program
