name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt install build-essential
    - name: Compile C program
      run: gcc program.c -o program
